title: Daniel's Page
author: Daniel Zhong
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My 1st page in github pages
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
